on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'


name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (TF ${{ matrix.config.tf }}) (TFHUB ${{ matrix.config.tfhub }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, tf: 'default', tfhub: 'NULL', r: 'release'}
        - { os: macOS-latest  , tf: 'default', tfhub: 'NULL', r: 'release'}
        - { os: ubuntu-latest , tf: 'default', tfhub: 'NULL', r: 'release'}
        - { os: ubuntu-latest , tf: 'nightly', tfhub: 'NULL', r: 'release', allow_failure: true}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@main
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
          Ncpus: '2'

      - uses: r-lib/actions/setup-pandoc@main

      - uses: r-lib/actions/setup-r-dependencies@main
        with:
          extra-packages: rcmdcheck remotes

      - name: Install dev r-tensorflow
        run: Rscript -e 'remotes::install_github("rstudio/tensorflow")'

      - name: Install miniconda
        run: Rscript -e 'reticulate::install_miniconda()'

      - name: Install tfhub r-pkg
        run: Rscript -e "remotes::install_local()"

      - name: Install tfhub py module
        run: Rscript -e 'tfhub::install_tfhub(${{ matrix.tfhub }})'

      - name: Check
        continue-on-error: ${{ matrix.config.allow_failure }}
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
